### PR TITLE
Add a test to check for missing migrations in test app models.

### PR DESCRIPTION
**Pull request by solarissmoke**
This will hopefully flag changes to the Treebeard models that
require a migration, to ensure that such changes are (a) evaluated for
their necessity and (b) shipped as part of a major release.

See #212 .

### CODE REVIEW

**Comment by tabo** [comment]
Excellent! I’m on my phone right now but I’ll take a closer look when I’m back on the PC. I see mssql tests failed? That seems odd

**Comment by solarissmoke** [comment]
MySQL failures seem unrelated - maybe just need to restart those builds (I don't seem to have permission to do that).

**Comment by tabo** [comment]
It just failed the tests for MSSQL again. Don't know much about them, but it's the second time this PR makes them fail. I don't know much about SQL Server, and even less about Django connecting to it, but if we are supporting it now, we need to sort this out.

**Comment by solarissmoke** [comment]
MSSQL failures are because `django-mssql-backend` [isn't compatible](https://github.com/ESSolutions/django-mssql-backend/pull/86) with Django>3.0 - it's been fixed on master but they've not cut a release.

**Comment by tabo** [comment]
Oh! Can we disable those tests until that's dealt with then?

**Comment by solarissmoke** [comment]
@tabo yes - I've commented those out of the appveyor config for now. Build should pass this time.

**Comment by solarissmoke** [comment]
A general comment on MSSQL - Django itself [does not](https://docs.djangoproject.com/en/3.1/ref/databases/) support MSSQL,  and there really isn't a robust third-party backend available. I don't think Treebeard can actually guarantee that it will work on MSSQL - and on that basis don't think we should actually declare support for it.

**Comment by tabo** [comment]
@solarissmoke Fantastic work on this PR. Thanks! And you make a fair point on MSSQL support, but if the tests are working with it, then it's safe to say that treebeard will work on it. My only concern is having 2 test infra and how slow those MSSQL tests are.

**Comment by solarissmoke** [comment]
@tabo it should be possible to move these tests to Github actions (thus we can drop both Travis and AppVeyor) - I will have a play with that when I have some more time.

**Pull request merged**
