### PR TITLE
Added support for SQL Server

### PR DESCRIPTION
**Pull request by rfosterslo**
Added SQL Server-specific syntax for update query.

### CODE REVIEW

**Comment by mkoistinen** [comment]
I just thought I'd pop in here to say that django CMS would also benefit from Treebeard's support for MS SQL Server. Also, considering recent announcements for MSSQL on Linux, this will become increasingly in demand.

**Comment by tabo** [comment]
I could merge this, but I have no way to know if it's actually working.

**Comment by jrief** [comment]
Is there a way to add an MSSQL server to the testing matrix on Travis-CI?

**Comment by mvantellingen** [comment]
This should be supported now via e228fe87d38e3ad58fe42dae2bf801522037c60f

**Pull request closed without merging**
