### PR TITLE
issues/django2

### PR DESCRIPTION
**Pull request by sasha0**

### CODE REVIEW

**Comment by jrief** [comment]
@sasha0 with that fix, can we approve the next version of django-treebeard for Django-2.0?

**Comment by sasha0** [comment]
Sure. We didn't find any other issues on Django 2.0 so far.

**Comment by jrief** [comment]
@sasha0 OK, then I will release a new version.

**Comment by jrief** [comment]
Just released version 4.3 on PyPI.
Thanks for the reminder.

**Pull request merged**
